#!/usr/bin/env ruby
# Combine two MikroTik **IPv6** country .rsc files into one
#
# Usage:
#   ruby combine_country_v6.rb <country1> <country2>
#
# The script expects the IPv6 .rsc files generated by the
# gen_mk_country_acl_ipv6.rb script to live in  countries_v6/.
# Example:
#   countries_v6/de.rsc
#   countries_v6/nl.rsc
# Produces:
#   countries_v6/de_nl.rsc

require 'fileutils'
require 'set'

def usage
  STDERR.puts 'Usage: ruby combine_country_v6.rb <country1> <country2>'
  exit 1
end

country1, country2 = ARGV
usage unless country1 && country2

DIR               = 'countries_v6'.freeze
file1             = File.join(DIR, "#{country1.downcase}.rsc")
file2             = File.join(DIR, "#{country2.downcase}.rsc")
output_file       = File.join(DIR, "#{country1.downcase}_#{country2.downcase}.rsc")
address_list_name = "#{country1.upcase}+#{country2.upcase} IPv6"

unless File.exist?(file1) && File.exist?(file2)
  STDERR.puts "Error: one or both .rsc files not found in #{DIR}/"
  exit 2
end

cidrs = Set.new                       # de-duplicate identical prefixes

[[file1, country1.upcase], [file2, country2.upcase]].each do |file, orig_cc|
  File.foreach(file) do |line|
    next if line.start_with?('#')
    # Matches: add list="XX IPv6" address=2001:db8::/32 comment="XX"
    if line =~ /^add .*? address=([0-9a-fA-F:\/]+)/
      cidrs << { cidr: Regexp.last_match(1), country: orig_cc }
    end
  end
end

File.open(output_file, 'w') do |f|
  f.puts "# MikroTik RouterOS IPv6 address list for #{country1.upcase}+#{country2.upcase}"
  f.puts "# Combined from: #{country1.downcase}.rsc, #{country2.downcase}.rsc"
  f.puts "# Generated at: #{Time.now}"
  f.puts "# Total IPv6 CIDR blocks: #{cidrs.size}"
  f.puts
  f.puts "/ipv6 firewall address-list"
  cidrs.each do |entry|
    f.puts(
      "add list=\"#{address_list_name}\" " \
      "address=#{entry[:cidr]} comment=\"#{address_list_name} (#{entry[:country]})\""
    )
  end
  f.puts
  f.puts "# Usage examples:"
  f.puts "# /ipv6 firewall filter"
  f.puts "# add action=accept chain=input src-address-list=\"#{address_list_name}\" " \
         "comment=\"Allow #{address_list_name} traffic\""
  f.puts "# add action=drop   chain=input src-address-list=\"#{address_list_name}\" " \
         "comment=\"Block #{address_list_name} traffic\""
end

puts "Combined IPv6 file written to: #{output_file}"
